# Part 1

In [2]:
import numpy as np

In [8]:
def in_bound(pos, map_matrix):
    max_row = map_matrix.shape[0]
    max_column = map_matrix.shape[1]
    return pos[0] in range(max_row) and pos[1] in range(max_column)

In [129]:
# def find_path(current_position, current_direction, room_map, visited_map, current_cost):
#     visited_map[current_position] = True
#     print('Visited', current_position)
#     if current_position == end_position:
#         recored_scores.append(current_cost)
#         return
#     next_positions = get_next_directions_and_cost(current_position, current_direction)
#     for p in next_positions:
#         next_direction, next_cost, next_position = p
#         if in_bound(next_position, room_map) and visited_map[next_position] == False and room_map[next_position] != '#':
#             find_path(next_position, next_direction, room_map, visited_map, current_cost+next_cost)

In [135]:
# with open('input_day16_test_2.txt') as file:
#     lines = file.readlines()
#     lines = [line.strip() for line in lines]
#     room_map = [[c for c in line] for line in lines]
#     room_map = np.array(room_map)
#     visited_map = np.array([[True if room_map[i,j] == '#' else False for j in range(room_map.shape[1])] for i in range(room_map.shape[0])])
#     print(room_map.shape, visited_map.shape)
    
#     start_position = (0,0)
#     end_position = (0,0)
#     for i in range(room_map.shape[0]):
#         for j in range(room_map.shape[1]):
#             if room_map[i,j] == 'S':
#                 start_position = (i,j)
#             elif room_map[i,j] == 'E':
#                 end_position = (i,j)
                
#     print(start_position, end_position)
    
#     recored_scores = []
#     find_path(start_position, 'right', room_map, visited_map, 0)

In [26]:
def spread(current_position, current_direction, room_map, cost_map, current_cost):
#     visited_map[current_position] = True
    cost_map[current_position] = current_cost
#     print('Visit', current_position)
    if current_position == end_position:
#         print('Visit ending position', current_position)
#         recored_scores.append(current_cost)
        return 
    next_positions = get_next_directions_and_cost(current_position, current_direction)
    print(next_positions)
    for p in next_positions:
        next_direction, next_cost, next_position = p
        if in_bound(next_position, room_map) and room_map[next_position] != '#':
            combined_next_cost = current_cost + next_cost
            print('Next cost', combined_next_cost, 'current cost', cost_map[next_position])
            if combined_next_cost <= cost_map[next_position] :
                spread(next_position, next_direction, room_map, cost_map, combined_next_cost)

In [27]:
from datetime import datetime
import numpy as np
with open('input_day16_test_1.txt') as file:
    lines = file.readlines()
    lines = [line.strip() for line in lines]
    room_map = [[c for c in line] for line in lines]
    room_map = np.array(room_map)
    cost_map = np.array([[1000000000 for j in range(room_map.shape[1])] for i in range(room_map.shape[0])])
    print(room_map.shape, cost_map.shape)
    
    start_position = (0,0)
    end_position = (0,0)
    for i in range(room_map.shape[0]):
        for j in range(room_map.shape[1]):
            if room_map[i,j] == 'S':
                start_position = (i,j)
            elif room_map[i,j] == 'E':
                end_position = (i,j)
                
    print(start_position, end_position)
    
    start = datetime.now()
    record_titles = []
    spread(start_position, 'right', room_map, cost_map, 0)
    end = datetime.now()
    time_execution = (end - start).total_seconds()
    print('Execution time', time_execution)
    
    
#     recored_scores = []

(15, 15) (15, 15)
(13, 1) (1, 13)
[('right', 1, (13, 2)), ('up', 1001, (12, 1)), ('down', 1001, (14, 1))]
Next cost 1 current cost 1000000000
[('right', 1, (13, 3)), ('up', 1001, (12, 2)), ('down', 1001, (14, 2))]
Next cost 2 current cost 1000000000
[('right', 1, (13, 4)), ('up', 1001, (12, 3)), ('down', 1001, (14, 3))]
Next cost 1001 current cost 1000000000
[('up', 1, (11, 1)), ('right', 1001, (12, 2)), ('left', 1001, (12, 0))]
Next cost 1002 current cost 1000000000
[('up', 1, (10, 1)), ('right', 1001, (11, 2)), ('left', 1001, (11, 0))]
Next cost 1003 current cost 1000000000
[('up', 1, (9, 1)), ('right', 1001, (10, 2)), ('left', 1001, (10, 0))]
Next cost 1004 current cost 1000000000
[('up', 1, (8, 1)), ('right', 1001, (9, 2)), ('left', 1001, (9, 0))]
Next cost 2005 current cost 1000000000
[('right', 1, (9, 3)), ('up', 1001, (8, 2)), ('down', 1001, (10, 2))]
Next cost 2006 current cost 1000000000
[('right', 1, (9, 4)), ('up', 1001, (8, 3)), ('down', 1001, (10, 3))]
Next cost 3007 curre

In [28]:
cost_map[end_position]

7036

In [29]:
cost_map[7,4],cost_map[8,5]

(4009, 3009)

In [42]:
def tracking_tiles_in_shortest_paths(current_position, room_map, cost_map, tiles):
    print('Current:', current_position, 'Current cost', cost_map[current_position])
    if current_position not in tiles:
        tiles.append(current_position)
    if current_position == start_position:
        print('Stop')
        return
    directions = ['up','down', 'left','right']
    backward_positions = []
    for d in directions:
        backward_positions.extend(get_next_directions_and_cost(current_position,d))
    for p in backward_positions:
        next_direction, next_cost, next_position = p
        if in_bound(next_position, room_map) and room_map[next_position] != '#':
            current_cost = cost_map[current_position]
            calculated_next_cost = current_cost - next_cost
#             print('Next cost', calculated_next_cost, 'current cost', cost_map[next_position])
            if calculated_next_cost == cost_map[next_position]:
                print('Next:', next_position, 'Next cost', cost_map[next_position])
#                 print(next_position, 'Next cost', calculated_next_cost, 'current cost', cost_map[next_position])
                tracking_tiles_in_shortest_paths(next_position, room_map, cost_map, tiles)

In [43]:
tiles = []
print(start_position, end_position)
tracking_tiles_in_shortest_paths(end_position, room_map, cost_map, tiles)
len(tiles),

(13, 1) (1, 13)
Current: (1, 13) Current cost 7036
Next: (2, 13) Next cost 7035
Current: (2, 13) Current cost 7035
Next: (3, 13) Next cost 7034
Current: (3, 13) Current cost 7034
Next: (4, 13) Next cost 7033
Current: (4, 13) Current cost 7033
Next: (5, 13) Next cost 7032
Current: (5, 13) Current cost 7032
Next: (6, 13) Next cost 7031
Current: (6, 13) Current cost 7031
Next: (7, 13) Next cost 7030
Current: (7, 13) Current cost 7030
Next: (8, 13) Next cost 7029
Current: (8, 13) Current cost 7029
Next: (9, 13) Next cost 7028
Current: (9, 13) Current cost 7028
Next: (10, 13) Next cost 7027
Current: (10, 13) Current cost 7027
Next: (11, 13) Next cost 7026
Current: (11, 13) Current cost 7026
Next: (12, 13) Next cost 7025
Current: (12, 13) Current cost 7025
Next: (13, 13) Next cost 6024
Current: (13, 13) Current cost 6024
Next: (13, 12) Next cost 6023
Current: (13, 12) Current cost 6023
Next: (13, 11) Next cost 5022
Current: (13, 11) Current cost 5022
Next: (12, 11) Next cost 5021
Current: (1

(37,)

In [32]:
print(room_map)

[['#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#']
 ['#' '.' '.' '.' '.' '.' '.' '.' '#' '.' '.' '.' '.' 'E' '#']
 ['#' '.' '#' '.' '#' '#' '#' '.' '#' '.' '#' '#' '#' '.' '#']
 ['#' '.' '.' '.' '.' '.' '#' '.' '#' '.' '.' '.' '#' '.' '#']
 ['#' '.' '#' '#' '#' '.' '#' '#' '#' '#' '#' '.' '#' '.' '#']
 ['#' '.' '#' '.' '#' '.' '.' '.' '.' '.' '.' '.' '#' '.' '#']
 ['#' '.' '#' '.' '#' '#' '#' '#' '#' '.' '#' '#' '#' '.' '#']
 ['#' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '#' '.' '#']
 ['#' '#' '#' '.' '#' '.' '#' '#' '#' '#' '#' '.' '#' '.' '#']
 ['#' '.' '.' '.' '#' '.' '.' '.' '.' '.' '#' '.' '#' '.' '#']
 ['#' '.' '#' '.' '#' '.' '#' '#' '#' '.' '#' '.' '#' '.' '#']
 ['#' '.' '.' '.' '.' '.' '#' '.' '.' '.' '#' '.' '#' '.' '#']
 ['#' '.' '#' '#' '#' '.' '#' '.' '#' '.' '#' '.' '#' '.' '#']
 ['#' 'S' '.' '.' '#' '.' '.' '.' '.' '.' '#' '.' '.' '.' '#']
 ['#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#']]


In [33]:
filled_room_map = room_map.copy()
for tile in tiles:
    filled_room_map[tile] = 'O'
    
print(filled_room_map)

[['#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#']
 ['#' '.' '.' '.' '.' '.' '.' '.' '#' '.' '.' '.' '.' 'O' '#']
 ['#' '.' '#' '.' '#' '#' '#' '.' '#' '.' '#' '#' '#' 'O' '#']
 ['#' '.' '.' '.' '.' '.' '#' '.' '#' '.' '.' '.' '#' 'O' '#']
 ['#' '.' '#' '#' '#' '.' '#' '#' '#' '#' '#' '.' '#' 'O' '#']
 ['#' '.' '#' '.' '#' '.' '.' '.' '.' '.' '.' '.' '#' 'O' '#']
 ['#' '.' '#' '.' '#' '#' '#' '#' '#' '.' '#' '#' '#' 'O' '#']
 ['#' '.' '.' '.' '.' 'O' 'O' 'O' 'O' 'O' 'O' 'O' '#' 'O' '#']
 ['#' '#' '#' '.' '#' 'O' '#' '#' '#' '#' '#' 'O' '#' 'O' '#']
 ['#' '.' '.' '.' '#' 'O' '.' '.' '.' '.' '#' 'O' '#' 'O' '#']
 ['#' '.' '#' '.' '#' 'O' '#' '#' '#' '.' '#' 'O' '#' 'O' '#']
 ['#' 'O' 'O' 'O' 'O' 'O' '#' '.' '.' '.' '#' 'O' '#' 'O' '#']
 ['#' 'O' '#' '#' '#' '.' '#' '.' '#' '.' '#' 'O' '#' 'O' '#']
 ['#' 'O' '.' '.' '#' '.' '.' '.' '.' '.' '#' 'O' 'O' 'O' '#']
 ['#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#' '#']]


In [34]:
print(cost_map[7,4],cost_map[7,5],cost_map[8,5] )

4009 3010 3009


In [39]:
print(cost_map[:,1:7])

[[1000000000 1000000000 1000000000 1000000000 1000000000 1000000000]
 [      5016       6017       6018       6019       6020       6021]
 [      5015 1000000000       7017 1000000000 1000000000 1000000000]
 [      5014       6015       6016       6017       6018 1000000000]
 [      5013 1000000000 1000000000 1000000000       7019 1000000000]
 [      5012 1000000000       3010 1000000000       6020       6019]
 [      5011 1000000000       3009 1000000000 1000000000 1000000000]
 [      4010       4009       3008       4009       3010       4011]
 [1000000000 1000000000       3007 1000000000       3009 1000000000]
 [      1004       2005       2006 1000000000       3008       4009]
 [      1003 1000000000       3005 1000000000       3007 1000000000]
 [      1002       2003       2004       2005       2006 1000000000]
 [      1001 1000000000 1000000000 1000000000       3007 1000000000]
 [         0          1          2 1000000000       3008       4009]
 [1000000000 1000000000 1000000000

In [168]:
start_position, end_position

((139, 1), (1, 139))

In [5]:
def get_next_position_by_direction(current_position, direction):
    if direction == 'up':
        return (current_position[0] - 1, current_position[1])
    elif direction == 'down':
        return (current_position[0] + 1, current_position[1])
    elif direction == 'right':
        return (current_position[0], current_position[1] + 1)
    elif direction == 'left':
        return (current_position[0], current_position[1] -1 )

In [6]:
directions = ['up','right','down','left']
def get_next_directions_and_cost(current_position, current_direction):
    if current_direction == 'up':
        return [('up', 1, get_next_position_by_direction(current_position, 'up')), \
                ('right', 1001, get_next_position_by_direction(current_position, 'right')),\
                ('left', 1001, get_next_position_by_direction(current_position, 'left'))]
    elif current_direction == 'right':
        return [('right', 1, get_next_position_by_direction(current_position, 'right')),\
                ('up', 1001, get_next_position_by_direction(current_position, 'up')),\
                ('down', 1001, get_next_position_by_direction(current_position, 'down'))]
    elif current_direction == 'down':
        return [('down', 1, get_next_position_by_direction(current_position, 'down')),\
                ('left', 1001, get_next_position_by_direction(current_position, 'left')),\
                ('right', 1001, get_next_position_by_direction(current_position, 'right'))]
    elif current_direction == 'left':
        return [('left', 1, get_next_position_by_direction(current_position, 'left')),\
                ('up', 1001, get_next_position_by_direction(current_position, 'up')),\
                ('down', 1001, get_next_position_by_direction(current_position, 'down'))]
  


In [8]:
# def get_next_positions(current_pos, current_direction, map_matrix):
#     current_row, current_col = current_pos
#     next_positions = [(current_row-1, current_col), (current_row, current_col+1), \
#                       (current_row+1, current_col), (current_row, current_col-1)]
#     result = []
#     for p in next_positions:
#         if in_bound(p, map_matrix):
#             if map_matrix[p] == '.':
#                 result.append(p)
#     return result

In [9]:
# def spread(current_position, hiking_trails, hiking_trails_array, map_matrix, trail_tail_visited_dic):
#     if map_matrix[current_position] == 9:
#         if trail_tail_visited_dic[current_position] == False:
#             hiking_trails_array.append(hiking_trails)
#             trail_tail_visited_dic[current_position] = True
#     else:
#         next_positions = get_next_positions(current_position, map_matrix)
#         if len(next_positions) == 0:
#             return
#         for n in next_positions:
#             new_hiking_trails = hiking_trails.copy()
#             new_hiking_trails.append(n)
#             spread(n, new_hiking_trails, hiking_trails_array, map_matrix,trail_tail_visited_dic)

In [10]:
# with open('input_day10.txt') as file:
#     lines = file.readlines()
#     lines = [line.strip() for line in lines]
#     map_matrix = [[int(col) for col in row] for row in lines]
#     map_matrix = np.array(map_matrix)

#     trail_head_positions = []
#     trail_tail_positions = []
#     for i in range(map_matrix.shape[0]):
#         for j in range(map_matrix.shape[1]):
#             if map_matrix[i,j] == 0:
#                 trail_head_positions.append((i,j))
#             if map_matrix[i,j] == 9:
#                 trail_tail_positions.append((i,j))
    
#     counter = 0
#     for head in trail_head_positions:
#         hiking_trails = []
#         hiking_trails_array = []
#         trail_tail_visited_map = {t: False for t in trail_tail_positions}
#         spread(head, hiking_trails, hiking_trails_array, map_matrix, trail_tail_visited_map)
#         counter = counter + len(hiking_trails_array)
#     print('Answer:', counter)