# Part 1

In [44]:
def in_bound(pos, map_matrix):
    max_row = map_matrix.shape[0]
    max_column = map_matrix.shape[1]
    return pos[0] in range(max_row) and pos[1] in range(max_column)

In [45]:
def spread(current_position, room_map, cost_map, current_cost, end_position):
#     visited_map[current_position] = True
    cost_map[current_position] = current_cost
#     print('Visit', current_position)
    if current_position == end_position:
#         print('Visit ending position', current_position)
#         recored_scores.append(current_cost)
        return 
    next_positions = [(current_position[0], current_position[1] -1 ), \
                       (current_position[0], current_position[1] + 1), \
                      (current_position[0] + 1, current_position[1]), \
                      (current_position[0] - 1, current_position[1])]
#     print(next_positions)
    for next_position in next_positions:
        if in_bound(next_position, room_map) and room_map[next_position] != '#':
            combined_next_cost = current_cost + 1
#             print('Next cost', combined_next_cost, 'current cost', cost_map[next_position])
            if combined_next_cost < cost_map[next_position]:
                spread(next_position, room_map, cost_map, combined_next_cost, end_position)

In [46]:
from datetime import datetime
import numpy as np
with open('input_day18.txt') as file:
    lines = file.readlines()
    lines = [line.strip() for line in lines]
    positions = [[int(c) for c in line.split(',')] for line in lines]
    positions = [(p[1], p[0]) for p in positions]
    
    max_length = 71
    memory_map = []
    for i in range(max_length):
        memory_map.append(['.']* max_length)
    memory_map = np.array(memory_map)
    
    cost_map = np.array([[10000 for j in range(memory_map.shape[1])] for i in range(memory_map.shape[0])])
    
    for i in range(1024):
        byte = positions[i]
        memory_map[byte] = '#'
    
#     print(memory_map)
    
    start_position = (0,0)
    end_position = (max_length-1, max_length - 1)
#     end_position = (10, 10)
    spread(start_position, memory_map, cost_map, 0, end_position)
    
    print('Answer:', cost_map[end_position])

Answer: 296


# Part 2

In [50]:
from datetime import datetime
import numpy as np
with open('input_day18.txt') as file:
    lines = file.readlines()
    lines = [line.strip() for line in lines]
    positions = [[int(c) for c in line.split(',')] for line in lines]
    positions = [(p[1], p[0]) for p in positions]
    
    max_length = 71
    memory_map = []
    for i in range(max_length):
        memory_map.append(['.']* max_length)
    memory_map = np.array(memory_map)
    
    cost_map = np.array([[10000 for j in range(memory_map.shape[1])] for i in range(memory_map.shape[0])])

In [ ]:
left = 0
right = len(positions) - 1

first_element = None
while True:
    middle = int((left + high)/2)
    memory_map_copy = memory_map.copy()
    for i in range(middle):
        byte = positions[i]
        memory_map_copy[byte] = '#'
    
#     print(memory_map)
    
    start_position = (0,0)
    end_position = (max_length-1, max_length - 1)
#     end_position = (10, 10)
    spread(start_position, memory_map_copy, cost_map, 0, end_position)
    
    if cost_map[end_position] != 10000:
        middle = int((middle + hight)/2)
    else:
        high = middle
        middle = int((left+hight))/2
        

In [49]:
cost_map[:11,:11]

array([[    0,     1,     2,     3,     4, 10000,    22,    21,    20,
           21,    22],
       [    1, 10000, 10000, 10000,     5, 10000, 10000, 10000,    19,
        10000,    23],
       [    2, 10000,     8,     7,     6, 10000,    16,    17,    18,
        10000,    24],
       [    3, 10000,     9, 10000, 10000, 10000,    15, 10000, 10000,
        10000, 10000],
       [    4, 10000,    10,    11,    12,    13,    14, 10000,    48,
           47,    46],
       [    5, 10000, 10000, 10000, 10000, 10000, 10000, 10000,    49,
        10000,    45],
       [    6, 10000,    60,    59,    58,    57,    58, 10000,    50,
        10000,    44],
       [    7, 10000,    59,    58,    57,    56, 10000, 10000,    51,
           52, 10000],
       [    8, 10000,    58,    57,    56,    55,    54,    53,    52,
        10000,   242],
       [    9, 10000, 10000, 10000, 10000, 10000,    55, 10000, 10000,
           60, 10000],
       [   10, 10000,    20,    21,    22, 10000,    56,    

In [19]:
from datetime import datetime
import numpy as np
with open('input_day18_test_1.txt') as file:
    lines = file.readlines()
    lines = [line.strip() for line in lines]
    positions = [[int(c) for c in line.split(',')] for line in lines]

In [20]:
len(lines)

25

In [21]:
positions = [(p[1], p[0]) for p in positions]

In [22]:
positions

[(4, 5),
 (2, 4),
 (5, 4),
 (0, 3),
 (1, 2),
 (3, 6),
 (4, 2),
 (5, 1),
 (6, 0),
 (3, 3),
 (6, 2),
 (1, 5),
 (2, 1),
 (5, 5),
 (5, 2),
 (5, 6),
 (4, 1),
 (4, 0),
 (4, 6),
 (1, 1),
 (1, 6),
 (0, 1),
 (5, 0),
 (6, 1),
 (0, 2)]

In [25]:
max_length = 7
memory_map = []
for i in range(max_length):
    memory_map.append(['.']* max_length)
memory_map = np.array(memory_map)
memory_map

array([['.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.'],
       ['.', '.', '.', '.', '.', '.', '.']], dtype='<U1')

In [27]:
for i in range(12):
    byte = positions[i]
    memory_map[byte] = '#'
print(memory_map)
    

[['.' '.' '.' '#' '.' '.' '.']
 ['.' '.' '#' '.' '.' '#' '.']
 ['.' '.' '.' '.' '#' '.' '.']
 ['.' '.' '.' '#' '.' '.' '#']
 ['.' '.' '#' '.' '.' '#' '.']
 ['.' '#' '.' '.' '#' '.' '.']
 ['#' '.' '#' '.' '.' '.' '.']]


In [28]:
start_position = (0,0)
end_position = (max_length-1, max_length - 1)

In [30]:
cost_map = np.array([[500 for j in range(memory_map.shape[1])] for i in range(memory_map.shape[0])])
cost_map

array([[500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500]])

In [35]:
spread(start_position, 'up', memory_map, cost_map, 0)

[('up', 1, (-1, 0)), ('right', 1, (0, 1)), ('left', 1, (0, -1))]
Next cost 1 current cost 500
[('right', 1, (0, 2)), ('up', 1, (-1, 1)), ('down', 1, (1, 1))]
Next cost 2 current cost 500
[('right', 1, (0, 3)), ('up', 1, (-1, 2)), ('down', 1, (1, 2))]
Next cost 2 current cost 500
[('down', 1, (2, 1)), ('left', 1, (1, 0)), ('right', 1, (1, 2))]
Next cost 3 current cost 500
[('down', 1, (3, 1)), ('left', 1, (2, 0)), ('right', 1, (2, 2))]
Next cost 4 current cost 500
[('down', 1, (4, 1)), ('left', 1, (3, 0)), ('right', 1, (3, 2))]
Next cost 5 current cost 500
[('down', 1, (5, 1)), ('left', 1, (4, 0)), ('right', 1, (4, 2))]
Next cost 6 current cost 500
[('left', 1, (4, -1)), ('up', 1, (3, 0)), ('down', 1, (5, 0))]
Next cost 7 current cost 500
[('up', 1, (2, 0)), ('right', 1, (3, 1)), ('left', 1, (3, -1))]
Next cost 8 current cost 500
[('up', 1, (1, 0)), ('right', 1, (2, 1)), ('left', 1, (2, -1))]
Next cost 9 current cost 500
[('up', 1, (0, 0)), ('right', 1, (1, 1)), ('left', 1, (1, -1))]
Ne

In [36]:
print(cost_map)

[[  0   1   2 500   8   9  10]
 [  3   2 500   6   7 500  11]
 [  4   3   4   5 500  13  12]
 [  5   4   5 500  15  14 500]
 [  6   5 500  17  16 500  24]
 [  7 500  19  18 500  22  23]
 [500 500 500  19  20  21  22]]


In [3]:

def get_next_position_by_direction(current_position, direction):
    if direction == 'up':
        return (current_position[0] - 1, current_position[1])
    elif direction == 'down':
        return (current_position[0] + 1, current_position[1])
    elif direction == 'right':
        return (current_position[0], current_position[1] + 1)
    elif direction == 'left':
        return (current_position[0], current_position[1] -1 )

# def get_next_directions_and_cost(current_position, current_direction):
#     return [('up', 1, get_next_position_by_direction(current_position, 'up')), \
#             ('right', 1, get_next_position_by_direction(current_position, 'right')),\
#             ('left', 1, get_next_position_by_direction(current_position, 'left')), \
#             ('down', 1, get_next_position_by_direction(current_position, 'down')),
#            ]
#     if current_direction == 'up':
#         return [('up', 1, get_next_position_by_direction(current_position, 'up')), \
#                 ('right', 1, get_next_position_by_direction(current_position, 'right')),\
#                 ('left', 1, get_next_position_by_direction(current_position, 'left'))]
#     elif current_direction == 'right':
#         return [('right', 1, get_next_position_by_direction(current_position, 'right')),\
#                 ('up', 1, get_next_position_by_direction(current_position, 'up')),\
#                 ('down', 1, get_next_position_by_direction(current_position, 'down'))]
#     elif current_direction == 'down':
#         return [('down', 1, get_next_position_by_direction(current_position, 'down')),\
#                 ('left', 1, get_next_position_by_direction(current_position, 'left')),\
#                 ('right', 1, get_next_position_by_direction(current_position, 'right'))]
#     elif current_direction == 'left':
#         return [('left', 1, get_next_position_by_direction(current_position, 'left')),\
#                 ('up', 1, get_next_position_by_direction(current_position, 'up')),\
#                 ('down', 1, get_next_position_by_direction(current_position, 'down'))]